// @flow

export const POCKETS__CHANGE_POCKET = 'POCKETS__CHANGE_POCKET';
export const POCKETS__CHANGE_AMOUNT = 'POCKETS__CHANGE_AMOUNT';
export const POCKETS__UPDATE_EXCHANGED = 'POCKETS__UPDATE_EXCHANGED';
